- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: "GZ_TO_ROS"

- ros_topic_name: "prosthesis/sensor/palm_imu"
  gz_topic_name: "prosthesis/sensor/palm_imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: "GZ_TO_ROS"

- ros_topic_name: "prosthesis/sensor/index_fsr"
  gz_topic_name: "prosthesis/sensor/index_fsr"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: "GZ_TO_ROS"

- ros_topic_name: "prosthesis/sensor/middle_fsr"
  gz_topic_name: "prosthesis/sensor/middle_fsr"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: "GZ_TO_ROS"

- ros_topic_name: "prosthesis/sensor/ring_fsr"
  gz_topic_name: "prosthesis/sensor/ring_fsr"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: "GZ_TO_ROS"

- ros_topic_name: "prosthesis/sensor/little_fsr"
  gz_topic_name: "prosthesis/sensor/little_fsr"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: "GZ_TO_ROS"

- ros_topic_name: "prosthesis/sensor/thumb_fsr"
  gz_topic_name: "prosthesis/sensor/thumb_fsr"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: "GZ_TO_ROS"

- ros_topic_name: "prosthesis/sensor/wrist_ft"
  gz_topic_name: "prosthesis/sensor/wrist_ft"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: "GZ_TO_ROS"

- ros_topic_name: "prosthesis/sensor/index_ft"
  gz_topic_name: "prosthesis/sensor/index_ft"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: "GZ_TO_ROS"

- ros_topic_name: "prosthesis/sensor/middle_ft"
  gz_topic_name: "prosthesis/sensor/middle_ft"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: "GZ_TO_ROS"

- ros_topic_name: "prosthesis/sensor/ring_ft"
  gz_topic_name: "prosthesis/sensor/ring_ft"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: "GZ_TO_ROS"

- ros_topic_name: "prosthesis/sensor/little_ft"
  gz_topic_name: "prosthesis/sensor/little_ft"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: "GZ_TO_ROS"

- ros_topic_name: "prosthesis/sensor/thumb_ft"
  gz_topic_name: "prosthesis/sensor/thumb_ft"
  ros_type_name: "geometry_msgs/msg/WrenchStamped"
  gz_type_name: "gz.msgs.Wrench"
  direction: "GZ_TO_ROS"

- ros_topic_name: "camera/point_cloud"
  gz_topic_name: "camera/point_cloud"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: "ROS_TO_GZ"